# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"saveDictToConfigJSON": "01_startup.ipynb",
         "loadConfigJSONToDict": "01_startup.ipynb",
         "DeepConfig": "01_startup.ipynb",
         "binify": "01_startup.ipynb",
         "SegCustomLabelList": "01_startup.ipynb",
         "SegCustomItemList": "01_startup.ipynb",
         "sens": "01_startup.ipynb",
         "spec": "01_startup.ipynb",
         "acc": "01_startup.ipynb",
         "Dice_Loss": "01_startup.ipynb",
         "my_Dice_Loss": "01_startup.ipynb",
         "saveResultsJSON": "01_startup.ipynb",
         "save_all_results": "01_startup.ipynb",
         "clean_tensor_lists": "01_startup.ipynb",
         "MLFlowTracker": "01_startup.ipynb"}

modules = ["startup.py"]

doc_url = "https://abalaji.github.io/oct/"

git_url = "https://github.com/abalaji/oct/tree/master/"

def custom_doc_links(name): return None
